# Generated by Django 2.0 on 2018-02-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='display_color',
            field=models.TextField(default='#000000', max_length=16),
        ),
    ]
