# Generated by Django 2.0.2 on 2018-02-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0002_auto_20180208_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='is_default',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='hide_by_default',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_default',
            field=models.BooleanField(),
        ),
    ]
