# Generated by Django 2.0.2 on 2018-02-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0003_auto_20180219_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='hide_by_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
