# Generated by Django 2.0 on 2018-02-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
    ]
