# Generated by Django 2.0.2 on 2018-02-19 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180208_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Only 10 digit integer allowed', regex='^[0-9]{10}$')]),
        ),
    ]
